id: cakephp-config

info:
  name: CakePHP Phinx Config File - Detect
  author: DhiyaneshDk
  severity: high
  description: CakePHP Phinx configuration file is exposed.  Phinx is a tool that allows developers to easily create database migrations in PHP.  Because of this highly sensitive database work Phinx needs database access and those parameters including username password host and other important variables are commonly kept in this file.
  reference:
    - https://book.cakephp.org/phinx/0/en/configuration.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 2
    verified: true
    shodan-query: html:"phinx.yml"
  tags: files,exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/phinx.yml"
      - "{{BaseURL}}/phinx.yaml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "host:"
          - "name:"
          - "user:"
          - "pass:"
          - "port:"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/08
# Enhanced by 6mile on 2023/06/05

