id: package-json

info:
  name: NPM config file exposed
  author: geeknik,afaq,noraj
  severity: low
  description: NPM configuration information was detected. All NPM packages contain a file usually in the project root called package.json - this file holds various metadata relevant to the project.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: config,exposure,securestack-fast
  reference:
    - https://docs.npmjs.com/cli/v9/configuring-npm/package-json
    - https://classic.yarnpkg.com/lang/en/docs/package-json/
    - https://pnpm.io/package_json
  metadata:
    max-request: 2
    verified: true
  tags: config,exposure,node,npm

http:
  - method: GET
    path:
      - "{{BaseURL}}/package.json"
      - "{{BaseURL}}/package-lock.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "name"
          - "version"
        condition: and

      - type: word
        part: header
        words:
          - "application/json"

      - type: status
        status:
          - 200
